name: Cowboy

on:
  push:
    branches:
      - master

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:

      - name: Git checkout
        uses: actions/checkout@v3
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      # - name: Update theme
      #   run: git submodule update --init --recursive

      - name: Setup hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "latest"
          extended: true

      - name: Build
        run: hugo

      - name: Permissions
        run: chmod 644 ./public/webfonts/*

      # GH PAGES
      # # Need to set root
      # - name: Deploy
      #   uses: peaceiris/actions-gh-pages@v3
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     publish_dir: ./public
      #     # personal_token: ${{ secrets.TOKEN }}
      #     # external_repository: <username>/<username>.github.io
      #     # publish_dir: ./public
      #     # #   keep_files: true
      #     # user_name: stav
      #     # user_email: steve@primesite.dev
      #     # publish_branch: master
      #     # #   cname: example.com

      # COWBOY
      - name: Deploy
        uses: "appleboy/scp-action@master"
        with:
          host: ${{ secrets.COWBOY_HOST }}
          port: 22
          username: ${{ secrets.COWBOY_USER }}
          key: ${{ secrets.COWBOY_KEY }}
          source: "./public"
          target: /srv/net.almeroth.stevenmichael
          overwrite: true
